services:
  app:
    image: golang:latest
    command: sh -c "go mod download && go mod verify && go run"
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./transmissions-pub:/app
    working_dir: /app
